# Generated by Django 3.2.7 on 2021-09-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='face_image',
        ),
        migrations.RemoveField(
            model_name='session',
            name='reference_frame',
        ),
        migrations.AlterField(
            model_name='session',
            name='report',
            field=models.JSONField(default={}),
        ),
    ]
